### ISSUE TITLE
LVI-setup ansible expects to be run in git repo, does not work in released tarball

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#2694] opened 2020-03-18 16:37 UTC
I'm trying to provision a new VM with a recent build of OE, ideally the v0.8.2 release. I download the release tarball (https://github.com/openenclave/openenclave/archive/0.8.2.tar.gz), untar, and try to install the dependencies via the included ansible playbook (`scripts/ansible/oe-contributors-acc-setup.yml`). This executes the new `lvi-setup.yml` step, which calls `git rev-parse`, which fails because we're not in a git repo.

The error as garbled by ansible is:

`fatal: [localhost]: FAILED! => {\"changed\": false, \"cmd\": \"git rev-parse --show-toplevel\", ..., \"msg\": \"non-zero return code\", \"rc\": 128, \"start\": \"2020-03-18 16:27:01.987462\", \"stderr\": \"fatal: not a git repository (or any of the parent directories): .git\", ...}`

Please remove the dependency on git, so that these playbooks can be used from the release tarball.

**Comment by jhand2** [comment] 2020-03-18 17:28
@mingweishih can you take a look at fixing this?

**Comment by mingweishih** [comment] 2020-03-18 17:31
@BRMcLaren @ionutbalutoiu I thought we get rid of that already. Can you double check?

**Comment by mingweishih** [comment] 2020-03-18 17:36
I think this is fixed by #2687.

**Comment by jhand2** [comment] 2020-03-18 17:43
Oh, so the problem is that the 0.8.2 release doesn't have the proper changes.

**Comment by mingweishih** [comment] 2020-03-18 17:44
cc @radhikaj

**Comment by eddyashton** [comment] 2020-03-18 17:44
@mingweishih Thanks, it looks like you're right and this is fixed by #2687, I'm able to run the playbook from [the tarball at this commit](https://github.com/openenclave/openenclave/tarball/5ee9bd3bf7d2df1be7073dd843c9a37b83c9d0d0). Any ETA on when this will be in a tagged release?

**Comment by ionutbalutoiu** [comment] 2020-03-18 17:45
> I think this is fixed by #2687.

Yep. You are correct. The PR https://github.com/openenclave/openenclave/pull/2687 merged some time ago, today.

**Comment by jhand2** [comment] 2020-03-19 23:11
@eddyashton The next planned release is v0.9 which I believe will be in mid-April

**Comment by radhikaj** [comment] 2020-03-24 17:08
I am closing this because  it's already fixed and there is a workaround in the meantime

**Closed** 2020-03-24 17:07 UTC
Labels: triaged
