### ISSUE TITLE
Use of headers intrinsics for AVX2

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4171] opened 2021-07-18 09:17 UTC
Hi, Team. I want to use headers `intrinsics` for AVX2 instructions, such as `#include <intrinsics/immintrin.h>`. Does OE support now?

One specific question when compiling `intrinsics` headers:
@anakrish  I hit many such issues in `apkman` environment
```
/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/mm_malloc.h:34:16: error: exception specification in declaration does not match previous declaration
extern "C" int posix_memalign (void **, size_t, size_t) throw ();
               ^
/home/dylan/.apkman/alpine-fs/usr/include/stdlib.h:99:5: note: previous declaration is here
int posix_memalign (void **, size_t, size_t);

/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:130:19: error: use of undeclared identifier '__builtin_ia32_addss'
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);
                  ^
/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:136:19: error: use of undeclared identifier '__builtin_ia32_subss'
  return (__m128) __builtin_ia32_subss ((__v4sf)__A, (__v4sf)__B);
                  ^
/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:142:19: error: use of undeclared identifier '__builtin_ia32_mulss'
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
                  ^
/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:148:19: error: use of undeclared identifier '__builtin_ia32_divss'; did you mean '__builtin_ia32_minss'?
  return (__m128) __builtin_ia32_divss ((__v4sf)__A, (__v4sf)__B);
                  ^~~~~~~~~~~~~~~~~~~~
                  __builtin_ia32_minss
/home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:142:19: note: '__builtin_ia32_minss' declared here
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
```

The second question is also about the `apkman` include directories:
@anakrish  When I compile the `.cpp` files as you explained, like:
```
add_custom_command(
  OUTPUT test.o dispatcher.o
  COMMAND apkman exec clang++ -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I/opt/openenclave/include ${CMAKE_CURRENT_SOURCE_DIR}/mHT/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/dispatcher.cpp
)
```
Although I place the headers in `-I${CMAKE_CURRENT_SOURCE_DIR}/include` = `/enclave/include` (NTL, GMP, HElib, intrinsics), it still searches the headers from the system path: `/home/dylan/.apkman/alpine-fs/usr/include/` (NTL, GMP, HElib, intrinsics)

**Comment by anakrish** [comment] 2021-07-18 11:03
OE does not ship with intrinsics headers.

> /home/dylan/.apkman/alpine-fs/usr/include/intrinsics/xmmintrin.h:130:19: error: use of undeclared identifier '__builtin_ia32_addss'
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);

This indicates that the compiler does not provide the intrinsics that the intrinsics headers expects.
Can you try with g++ instead of clang++ and see if it compiles? 

> COMMAND apkman exec clang++ -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I/opt/openenclave/include ...

You need to refactor your code so that when compiling C++ code using apkman, you don't need OE headers.

**Comment by DylanWangWQF** [comment] 2021-07-18 11:16
@anakrish 
> This indicates that the compiler does not provide the intrinsics that the intrinsics headers expect.
Can you try with g++ instead of clang++ and see if it compiles?

I will have a try, in this case, I have to recompile libs with g++.

> you need to refactor your code so that when compiling C++ code using apkman, you don't need OE headers.

In `dispatcher.cpp`: I use some OE functions, like:  `oe_host_malloc` to allocate host memory. What I mean is we place `NTL`, `gmp` and `intrinsics` headers in `${CMAKE_CURRENT_SOURCE_DIR}/include`, while the program still seraches these headers from `apkman` path `/home/dylan/.apkman/alpine-fs/usr/include/`

**Comment by anakrish** [comment] 2021-07-18 11:20
>> I use some OE functions, like: oe_host_malloc

Instead of including OE headers in these C++ files, it is better to just declare these functions yourself. The issue with putting OE directories in path when compiling using alpine linux (apkman) is that it becomes hard to reason about which headers get picked up.

**Comment by DylanWangWQF** [comment] 2021-07-18 11:31
@anakrish 
Sry, I'm not that familiar with OE functions and C++. The implementation of [oe_host_malloc](https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/enclave/core/hostcalls.c#L54):
```
void* oe_host_malloc(size_t size)
{
    uint64_t arg_in = size;
    uint64_t arg_out = 0;

    if (oe_ocall(OE_OCALL_MALLOC, arg_in, &arg_out) != OE_OK)
    {
        return NULL;
    }

    if (arg_out && !oe_is_outside_enclave((void*)arg_out, size))
        oe_abort();

    return (void*)arg_out;
}
```
If I implement these functions, I have to implement all of the related invoked functions?

**Comment by DylanWangWQF** [comment] 2021-07-18 11:40
before adding `intrinsics ` headers, the program runs correctly even if I add the OE headers, maybe no conflicts in current codes. I mean implementing these functions may be a little difficult for me and my whole program.

**Comment by anakrish** [comment] 2021-07-18 11:45
You don't need to implement them; you just need to **declare** them:
ie:
```c
void* oe_host_malloc(size_t size); // no need of function body.
```

Did it work with g++? If so, then you are all set.

**Comment by anakrish** [comment] 2021-07-18 12:00
I created the following file:
```c
// test.cpp
#include <immintrin.h>
#include <mm_malloc.h>
```

I'm able to compile successfully using clang++ and g++:
```bash
anakrish@acc:~/tmp$ apkman exec clang++ -std=c++17 -c test.cpp
anakrish@acc:~/tmp$ apkman exec g++ -std=c++17 -c test.cpp
```

**Comment by DylanWangWQF** [comment] 2021-07-18 12:11
I'm testing it. I will post the result later. It's a little slower since I'm using another computer

**Comment by DylanWangWQF** [comment] 2021-07-18 12:20
@anakrish 
I test the program with gcc/g++ 7.5, while getting a lot of errors, it seems it's not about `intrinsics`:
```
/home/dylan/.apkman/alpine-fs/usr/include/helib/EncryptedArray.h:1654:7:   required from ‘void helib::EncryptedArray::dispatch(Args&& ...) const [with T = helib::PlaintextArray::ConstructorImpl; Args = {helib::PlaintextArray&}]’
/home/dylan/.apkman/alpine-fs/usr/include/helib/EncryptedArray.h:2038:39:   required from here
/home/dylan/.apkman/alpine-fs/usr/include/c++/10.2.1/bits/stl_uninitialized.h:619:18: error: ‘value’ is not a member of ‘std::is_copy_assignable<NTL::zz_pX>’
       const bool __assignable = is_copy_assignable<_ValueType>::value;
                  ^~~~~~~~~~~~
In file included from /home/dylan/.apkman/alpine-fs/usr/include/c++/10.2.1/memory:83:0,
                 from /home/dylan/.apkman/alpine-fs/usr/include/helib/NumbTh.h:30,
                 from /home/dylan/.apkman/alpine-fs/usr/include/helib/DoubleCRT.h:19,
                 from /home/dylan/.apkman/alpine-fs/usr/include/helib/helib.h:22,
                 from /home/dylan/mysamples/foSDSC_obl/enclave/dispatcher.h:8,
                 from /home/dylan/mysamples/foSDSC_obl/enclave/ecalls.cpp:4:

/home/dylan/.apkman/alpine-fs/usr/include/c++/10.2.1/bits/stl_uninitialized.h:150:42: error: ‘value’ is not a member of ‘std::is_constructible<std::complex<double>, const std::complex<double>&>’
  __uninit_copy(__first, __last, __result);
                                          ^
/home/dylan/.apkman/alpine-fs/usr/include/c++/10.2.1/bits/stl_uninitialized.h:144:18: error: ‘value’ is not a member of ‘std::is_assignable<std::complex<double>&, const std::complex<double>&>’
       const bool __assignable = is_assignable<_RefType2, _RefType1>::value;
                  ^~~~~~~~~~~~

```

**Comment by DylanWangWQF** [comment] 2021-07-18 12:23
Here is the detailed log:
[make.log](https://github.com/openenclave/openenclave/files/6836236/make.log)

**Comment by DylanWangWQF** [comment] 2021-07-18 12:30
Is it due to gcc/g++ version?

**Comment by anakrish** [comment] 2021-07-18 12:40
Can you try out the tiny example I gave in my previous post?

**Comment by anakrish** [comment] 2021-07-18 12:42
How are you getting gcc version 7.5? 
For me, `apkman exec g++ -v` gives 10.2.1 and `apkman exec clang++ -v ` gives 10.0.1.

**Comment by DylanWangWQF** [comment] 2021-07-18 12:42
@anakrish 
The above tiny example can be done successfully in my machine
```
apkman exec clang++ -std=c++17 -c test.cpp
test.o
apkman exec g++ -std=c++17 -c test.cpp
test.o
```

**Comment by DylanWangWQF** [comment] 2021-07-18 12:43
> How are you getting gcc version 7.5?
> For me, `apkman exec g++ -v` gives 10.2.1 and `apkman exec clang++ -v ` gives 10.0.1.

Sry, I forgot that in `apkman` it's different. g++/gcc is 7.5 in my Ubuntu

**Comment by DylanWangWQF** [comment] 2021-07-18 12:45
Here is my enclave/CMakeLists.txt:
```
add_custom_command(
  OUTPUT fosdscobl_t.h fosdscobl_t.c fosdscobl_args.h
  DEPENDS ${CMAKE_SOURCE_DIR}/fosdscobl.edl
  COMMAND
    openenclave::oeedger8r --trusted ${CMAKE_SOURCE_DIR}/fosdscobl.edl
    --search-path ${OE_INCLUDEDIR} --search-path
    ${OE_INCLUDEDIR}/openenclave/edl/sgx)

# add_custom_command(
#   OUTPUT dispatcher.o
#   COMMAND apkman exec clang++ -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I/opt/openenclave/include ${CMAKE_CURRENT_SOURCE_DIR}/dispatcher.cpp
# )

add_custom_command(
  OUTPUT test1.o test2.o dispatcher.o
  COMMAND apkman exec clang++ -mavx2 -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I/opt/openenclave/include ${CMAKE_CURRENT_SOURCE_DIR}/mHT/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/dispatcher.cpp
)

add_executable(enclave ecalls.cpp dispatcher.o test1.o test2.o stubs.c ${CMAKE_CURRENT_BINARY_DIR}/fosdscobl_t.c)


target_compile_definitions(enclave PUBLIC OE_API_VERSION=2)

# APKMAN_ROOT /home/dylan/.apkman/alpine-fs
message("APKMAN_ROOT ${APKMAN_ROOT}")

target_include_directories(
  enclave
  PRIVATE ${CMAKE_CURRENT_BINARY_DIR}
          #lib include path
          ${CMAKE_CURRENT_SOURCE_DIR}
          # C++
          ${APKMAN_ROOT}/usr/include/c++/10.2.1
          ${APKMAN_ROOT}/usr/include/c++/10.2.1/x86_64-alpine-linux-musl
          # C
          ${APKMAN_ROOT}/usr/include)

target_compile_options(
  enclave
  PRIVATE
  -g
  -Wno-shorten-64-to-32
  -Wno-bitwise-op-parentheses
  -Wno-shift-op-parentheses
  -Wno-sign-conversion
  -Wno-unused-parameter
  -Wno-implicit-int-conversion
  -ftls-model=local-exec)

if (WIN32)
  maybe_build_using_clangw(enclave)
endif ()

if (USE_AVX2)
  target_compile_options(enclave PRIVATE -mavx2)
  target_compile_definitions(enclave PRIVATE -DUSE_AVX2)
endif (USE_AVX2)

target_link_libraries(
    enclave 
    -nostdlib
    # Add library path and libraries.
    -L${CMAKE_CURRENT_SOURCE_DIR}/lib
    libhelib.a
    libntl.a
    libgmp.a
    openenclave::oecore
    -L${APKMAN_ROOT}/usr/lib
    libstdc++.a
    -L${APKMAN_ROOT}/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1
    libgcc.a
    openenclave::oeenclave
    openenclave::oecrypto${OE_CRYPTO_LIB}
    openenclave::oelibcxx
    openenclave::oelibc
    # Use apkman's ld to avoid bug with Ubuntu 18.04's binutils.
    -fuse-ld=${CMAKE_CURRENT_SOURCE_DIR}/ld
    # Emit warnings for unresolved symbols.
    -Wl,--warn-unresolved-symbols
    -Wl,--wrap,setlocale
    -Wl,--wrap,oe_SYS_clock_gettime_impl)
```

**Comment by anakrish** [comment] 2021-07-18 12:53
> @anakrish
> The above tiny example can be done successfully in my machine
> 
> ```
> apkman exec clang++ -std=c++17 -c test.cpp
> test.o
> apkman exec g++ -std=c++17 -c test.cpp
> test.o
> ```

Then intrinsics work correctly on your machine.

My suggestion would be to 
- avoid /opt/openenclave as described before by *declaring* necessary function.
- Start with the tiny test.cpp and add code until you reach the specific compile error.

**Comment by DylanWangWQF** [comment] 2021-07-18 12:53
the header directories structure:
```
/enclave
    /include
         /helib
         /NTL
         /intrinsics
         /gmp.h
    /lib
    dispatcher.h/.cpp
    ecalls.cpp
```

**Comment by DylanWangWQF** [comment] 2021-07-18 12:59
@anakrish 
I test it with another tiny example: `intrinsics/immintrin.h`. while hitting the same issue
```
// test.cpp
#include <intrinsics/immintrin.h>

apkman exec clang++ -mavx2 -std=c++17 -c test.cpp
```
```
In file included from test.cpp:3:
In file included from /usr/include/intrinsics/immintrin.h:29:
In file included from /usr/include/intrinsics/xmmintrin.h:34:
/usr/include/intrinsics/mm_malloc.h:34:16: error: exception specification in declaration does not match previous declaration
extern "C" int posix_memalign (void **, size_t, size_t) throw ();
               ^
/usr/include/stdlib.h:99:5: note: previous declaration is here
int posix_memalign (void **, size_t, size_t);
    ^
In file included from test.cpp:3:
In file included from /usr/include/intrinsics/immintrin.h:29:
/usr/include/intrinsics/xmmintrin.h:130:19: error: use of undeclared identifier '__builtin_ia32_addss'
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:136:19: error: use of undeclared identifier '__builtin_ia32_subss'
  return (__m128) __builtin_ia32_subss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:142:19: error: use of undeclared identifier '__builtin_ia32_mulss'
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:148:19: error: use of undeclared identifier '__builtin_ia32_divss'; did you mean '__builtin_ia32_minss'?
  return (__m128) __builtin_ia32_divss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:142:19: note: '__builtin_ia32_minss' declared here
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:242:10: error: use of undeclared identifier '__builtin_ia32_andps'; did you mean '__builtin_ia32_haddps'?
  return __builtin_ia32_andps (__A, __B);
         ^
/usr/include/intrinsics/xmmintrin.h:242:10: note: '__builtin_ia32_haddps' declared here
/usr/include/intrinsics/xmmintrin.h:248:10: error: use of undeclared identifier '__builtin_ia32_andnps'
  return __builtin_ia32_andnps (__A, __B);
         ^
/usr/include/intrinsics/xmmintrin.h:254:10: error: use of undeclared identifier '__builtin_ia32_orps'
  return __builtin_ia32_orps (__A, __B);
         ^
/usr/include/intrinsics/xmmintrin.h:260:10: error: use of undeclared identifier '__builtin_ia32_xorps'
  return __builtin_ia32_xorps (__A, __B);
         ^
/usr/include/intrinsics/xmmintrin.h:288:19: error: use of undeclared identifier '__builtin_ia32_movss'
  return (__m128) __builtin_ia32_movss ((__v4sf) __A,
                  ^
/usr/include/intrinsics/xmmintrin.h:298:19: error: use of undeclared identifier '__builtin_ia32_movss'
  return (__m128) __builtin_ia32_movss ((__v4sf) __A,
                  ^
/usr/include/intrinsics/xmmintrin.h:326:19: error: use of undeclared identifier '__builtin_ia32_movss'
  return (__m128) __builtin_ia32_movss ((__v4sf) __A,
                  ^
/usr/include/intrinsics/xmmintrin.h:336:19: error: use of undeclared identifier '__builtin_ia32_movss'
  return (__m128) __builtin_ia32_movss ((__v4sf) __A,
                  ^
/usr/include/intrinsics/xmmintrin.h:380:19: error: use of undeclared identifier '__builtin_ia32_cmpgtps'; did you mean '__builtin_ia32_cmpltps'?
  return (__m128) __builtin_ia32_cmpgtps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:368:19: note: '__builtin_ia32_cmpltps' declared here
  return (__m128) __builtin_ia32_cmpltps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:386:19: error: use of undeclared identifier '__builtin_ia32_cmpgeps'; did you mean '__builtin_ia32_cmpleps'?
  return (__m128) __builtin_ia32_cmpgeps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:374:19: note: '__builtin_ia32_cmpleps' declared here
  return (__m128) __builtin_ia32_cmpleps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:410:19: error: use of undeclared identifier '__builtin_ia32_cmpngtps'; did you mean '__builtin_ia32_cmpnltps'?
  return (__m128) __builtin_ia32_cmpngtps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:380:19: note: '__builtin_ia32_cmpnltps' declared here
  return (__m128) __builtin_ia32_cmpgtps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:416:19: error: use of undeclared identifier '__builtin_ia32_cmpngeps'; did you mean '__builtin_ia32_cmpnleps'?
  return (__m128) __builtin_ia32_cmpngeps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:386:19: note: '__builtin_ia32_cmpnleps' declared here
  return (__m128) __builtin_ia32_cmpgeps ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/include/intrinsics/xmmintrin.h:602:19: error: use of undeclared identifier '__builtin_ia32_cvtsi2ss'; did you mean '__builtin_ia32_cvtsd2ss'?
  return (__m128) __builtin_ia32_cvtsi2ss ((__v4sf) __A, __B);
                  ^
/usr/include/intrinsics/xmmintrin.h:602:19: note: '__builtin_ia32_cvtsd2ss' declared here
/usr/include/intrinsics/xmmintrin.h:602:58: error: cannot initialize a parameter of type '__attribute__((__vector_size__(2 * sizeof(double)))) double' (vector of 2 'double' values) with an lvalue of type
      'int'
  return (__m128) __builtin_ia32_cvtsi2ss ((__v4sf) __A, __B);
```

**Comment by anakrish** [comment] 2021-07-18 13:00
You can just delete the `enclave/include/intrinsics` folder. 

The correct intrinsics headers are already available in the alpine environment.

**Comment by DylanWangWQF** [comment] 2021-07-18 13:16
@anakrish 
The tiny example now runs correctly.
I have a .h file that refs the `#include <immintrin.h>`. But cannot find this file when `make` file
```
// obl_primitives.h
#pragma once
#include <cstddef>
#include <cstdint>
#include <type_traits>
#include <cstring>

#ifdef USE_AVX2
#include <immintrin.h>
#endif
```

```
apkman exec clang++ -mavx2 -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I/opt/openenclave/include ${CMAKE_CURRENT_SOURCE_DIR}/mHT/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/dispatcher.cpp
```
```
In file included from /home/dylan/mysamples/foSDSC_obl/enclave/ecalls.cpp:4:
In file included from /home/dylan/mysamples/foSDSC_obl/enclave/dispatcher.h:11:
/home/dylan/mysamples/foSDSC_obl/enclave/include/obl/obl_primitives.h:11:10: fatal error: 'immintrin.h' file not found
#include <immintrin.h>
         ^~~~~~~~~~~~~
```

**Comment by DylanWangWQF** [comment] 2021-07-18 13:17
In fact, we build NTL with apkman, and it also includes this header but no issues
```
#include <NTL/tools.h>
#include <immintrin.h>
```

**Comment by anakrish** [comment] 2021-07-18 13:25
```
In file included from /home/dylan/mysamples/foSDSC_obl/enclave/ecalls.cpp:4:
In file included from /home/dylan/mysamples/foSDSC_obl/enclave/dispatcher.h:11:
/home/dylan/mysamples/foSDSC_obl/enclave/include/obl/obl_primitives.h:11:10: fatal error: 'immintrin.h' file not found
#include <immintrin.h>
```

Again, this is just code refactoring. You want to cleanly isolate the components that are compiled using apkman and those that are compiled using enclave headers.

Avoid using immintrin.h in dispatcher.h. Use it only in dispatcher.cpp.

**Comment by DylanWangWQF** [comment] 2021-07-18 14:01
@anakrish  I'm trying to isolate the code to be compatible in apkman according to your suggestions.
Sry for my noise, what I do:
```
// comment OE headers in dispatcher.h
// #include <openenclave/enclave.h>

then just declare `oe_host_malloc` in dispatcher.h:
class ecall_dispatcher
{
public:
    ecall_dispatcher();
    int enclave_init(uint8_t* hecontext, size_t context_len, uint8_t** rawCtxt, size_t* rawCtxt_len, size_t* num_rawCtxt);
    int multipleCtxtsTransform(uint8_t* ectxt, size_t ectxt_len, size_t num_ectxt, uint8_t** octxt, size_t* octxt_len, size_t* num_octxt);
    void close();
  private:
    int HTtrain(vector<Ctxt>& ReceivedCtxts, vector<Ctxt>& ReturnedCtxts);
    void DecryptMat(vector<Ctxt>& ReceivedCtxts, vector<map<size_t, Mat<size_t>>>& countedMat, vector<pair<size_t, size_t>>& indiceAndsize);
    void EncryptMat(vector<Ctxt>& ReturnedCtxts, vector<string>& Allleafmatrix);
   
    void* oe_host_malloc(size_t size);
}
```
```
also remove OE header in dispatcher.cpp:
#include <string.h>
#include <NTL/matrix.h>
#include <vector>

#include "dispatcher.h"
#include "trace.h"
```
Is this what you said before?

**Comment by DylanWangWQF** [comment] 2021-07-18 21:27
@anakrish  Update about `immintrin.h`
According to your suggestions, I declare `oe_host_malloc` in `dispatcher.h` as shown above.
This time, `immintrin.h` can be compiled without errors while `oe_host_malloc` got `undefined reference` warning and then failed to run.
```
ld: dispatcher.o: in function `ecall_dispatcher::enclave_init(unsigned char*, unsigned long, unsigned char**, unsigned long*, unsigned long*)':
/home/dylan/mysamples/foSDSC_obl/enclave/dispatcher.cpp:133: warning: undefined reference to `ecall_dispatcher::oe_host_malloc(unsigned long)'
ld: dispatcher.o: in function `ecall_dispatcher::multipleCtxtsTransform(unsigned char*, unsigned long, unsigned long, unsigned char**, unsigned long*, unsigned long*)':
/home/dylan/mysamples/foSDSC_obl/enclave/dispatcher.cpp:203: warning: undefined reference to `ecall_dispatcher::oe_host_malloc(unsigned long)'
```

**Comment by DylanWangWQF** [comment] 2021-07-19 02:28
@anakrish 
Compile it successfully by including the `-I${APKMAN_ROOT}/opt/openenclave/include` path.
I even don't know why this is successful, although I can compile and run it.
```
apkman exec clang++ -mavx2 -std=c++17 -fPIE -g -c -I${CMAKE_CURRENT_SOURCE_DIR}/include -I${APKMAN_ROOT}/opt/openenclave/include ${CMAKE_CURRENT_SOURCE_DIR}/mHT/*.cpp ${CMAKE_CURRENT_SOURCE_DIR}/dispatcher.cpp
```

**Comment by anakrish** [comment] 2021-07-19 04:50
@DylanWangWQF 

```c
// comment OE headers in dispatcher.h
// #include <openenclave/enclave.h>

then just declare `oe_host_malloc` in dispatcher.h:
class ecall_dispatcher
{
public:
..
private:
**void* oe_host_malloc(size_t size);**
};
```

If you want to use dispatcher.h in both cpp files compiled using apkman as well as cpp files normally compiled using the C++ compiler on your machine, then dispatcher.h must have only C code. It cannot have classes etc.

Alternatively, you can ensure that all C++ code is compiled using apkman. Therefore you'd compile ecalls.cpp as well using apkman, add add include paths for appropriate headers.

**Comment by anakrish** [comment] 2021-07-20 15:08
@DylanWangWQF I'm closing this since the issue has been addressed and there is nothing to be done on the OE side.

**Comment by dthaler** [comment] 2021-07-20 16:30
@anakrish you say "there is nothing to be done on the OE side"... we discussed in triage meeting yesterday and asked why a header of this name doesn't ship with OE?

**Comment by anakrish** [comment] 2021-07-20 16:41
Ok. I believe shipping intrinsics headers is already covered by #3795. Isn't this a dupe?

**Comment by anakrish** [comment] 2021-07-21 04:56
Dupe of #3795

**Closed by anakrish** 2021-07-21 04:56 UTC
Labels: API, feature, triaged
