### ISSUE TITLE
Problem in executing the example attested_tls on Ubuntu 18 with no virtual machines

### ISSUE THREAD

**Issue by VincenzoGallicchio** [openenclave/openenclave#3429] opened 2020-08-22 12:16 UTC
Hi everybody, I've been trying to use the attested_tls example locally but it gets stuck and I can't figure out why, can someone help me? Thank you

It successfully starts the enclave tls server which waits for connections but then, when the client tries to reach it,  it stops.
I think it's a problem related to the remote attestation feature

Here's the error:

Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
]TLS server:
Setting up the SSL configuration....
TLS server:Waiting for a client connection request...
server name = [localhost]
server port = [12341]
Host: Creating two enclaves
Host: Enclave library /home/vincenzo/Scrivania/attested_tls/build/client/enc/tls_client_enc.signed
Host: Enclave successfully created.
Host: launch TLS client to initiate TLS connection
TLS client:
Seeding the random number generator...
TLS client:Connecting to tcp: localhost/12341...
TLS client:Connected to server @localhost.12341
TLS client:Generating the certificate and private key
TLS server:mbedtls_net_accept returned successfully.(listen_fd = 3) (client_fd = 4) 
TLS server:Performing the SSL/TLS handshake...
public key used:
[-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjigMYax8iPVkVRTVOS7aFcLaleJA
ZgZQHd8Cvm2n6IqWNIh6j+PXmgAg1+WG1E2FWuqs77DBFywdK6ZtN9vWqA==
-----END PUBLIC KEY-----
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
]TLS client:Setting up the SSL/TLS structure...
TLS client:mbedtls_ssl_config_defaults returned successfully
TLS client:Performing the SSL/TLS handshake...
TLS client:Received TLS certificate from server
TLS client:cert_verify_callback with depth = 0
TLS client:crt->version = 3 cert_size = 5064
2020-08-22T12:17:34.000000Z [(H)ERROR] tid(0x7fcf14011b80) | :OE_QUOTE_PROVIDER_CALL_ERROR [/source/host/sgx/sgxquoteprovider.c:oe_get_sgx_quote_verification_collateral:86]
2020-08-22T12:17:34.000000Z [(H)ERROR] tid(0x7fcf14011b80) | :OE_QUOTE_PROVIDER_CALL_ERROR [/source/host/sgx/ocalls.c:oe_get_quote_verification_collateral_ocall:182]
2020-08-22T12:17:34.000000Z [(H)ERROR] tid(0x7fcf14011b80) | :OE_ENCLAVE_ABORTING [/source/host/calls.c:oe_call_enclave_function_by_table_id:91]
Host: launch_tls_client failed

**Comment by yentsanglee** [comment] 2020-08-24 05:10
It failed in az-dcap-client. Try setting AZDCAP_DEBUG_LOG_LEVEL environment variable to INFO (as instructed in [README](https://github.com/microsoft/Azure-DCAP-Client/blob/master/README.md))  and re-run the sample. Watch out for libdcap_quoteprov.so errors.

**Comment by anakrish** [comment] 2020-08-24 18:12
Waiting for response from issue filer.

**Comment by VincenzoGallicchio** [comment] 2020-08-25 10:50
Unfortunatelly the attested_tls is still no working.
Here's the result of ctest:
98% tests passed, 6 tests failed out of 273

Total Test time (real) = 247.47 sec

The following tests did not run:
	 73 - tests/bigmalloc (Skipped)
	219 - tests/report_attestation_without_enclave (Skipped)

The following tests FAILED:
	 62 - tests/tls_e2e (Child aborted)
	 69 - tests/attestation_cert_api (Failed)
	 70 - tests/attestation_plugin (Child aborted)
	 71 - tests/attestation_plugin_cert (Failed)
	218 - tests/report (Child aborted)
	273 - samples (Failed)
Errors while running CTest

And here's the output of make run on attested_tls:
StartingTLS client:


TLS client:connected to localhost:12341
TLS server:mbedtls_net_accept returned successfully.(listen_fd = 3) (client_fd = 4) 
TLS server:Performing the SSL/TLS handshake...
TLS client:verify_callback called with preverify_ok=0
TLS client:self-signed certificated detected
TLS client:verify_callback called with preverify_ok=1
TLS client:der=0x563b15430dd0 buff=0x563b15432198 buff moved by 5064 offset der_len=5064
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | Platform TCB (4) is not up-to-date (oe_result_t=OE_TCB_LEVEL_INVALID) [/source/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:739]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | Failed to parse TCB info or Platform TCB is not up-to-date. OE_TCB_LEVEL_INVALID (oe_result_t=OE_TCB_LEVEL_INVALID) [/source/common/sgx/collateral.c:oe_validate_revocation_list:341]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | :OE_INVALID_PARAMETER [/source/host/crypto/openssl/cert.c:oe_cert_free:574]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | Failed to validate revocation info. OE_TCB_LEVEL_INVALID (oe_result_t=OE_TCB_LEVEL_INVALID) [/source/common/sgx/quote.c:oe_get_sgx_quote_validity:666]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | Failed to validate quote. OE_TCB_LEVEL_INVALID (oe_result_t=OE_TCB_LEVEL_INVALID) [/source/common/sgx/quote.c:oe_verify_quote_with_sgx_endorsements:506]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | :OE_TCB_LEVEL_INVALID [/source/common/sgx/quote.c:oe_verify_sgx_quote:471]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | :OE_TCB_LEVEL_INVALID [/source/host/sgx/hostverify_report.c:oe_verify_remote_report:46]
2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | :OE_TCB_LEVEL_INVALID [/source/common/sgx/tlsverifier.c:oe_verify_attestation_certificate:134]
TLS client:result=OE_TCB_LEVEL_INVALID
TLS client:Verifying SGX certificate extensions ... failed
TLS client:Error: Could not establish an SSL session ret2=-1 SSL_get_error()=1
TLS client: failed
TLS server:failed
  ! mbedtls_ssl_handshake returned -0x7780
TLS server:server communication error -30592
TLS server:Last error was: -30592 - SSL - A fatal alert message was received from our peer

Host: Terminating enclaves
CMakeFiles/run.dir/build.make:59: recipe for target 'CMakeFiles/run' failed
make[3]: *** [CMakeFiles/run] Error 1
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/run.dir/all' failed
make[2]: *** [CMakeFiles/run.dir/all] Error 2
CMakeFiles/Makefile2:83: recipe for target 'CMakeFiles/run.dir/rule' failed
make[1]: *** [CMakeFiles/run.dir/rule] Error 2
Makefile:118: recipe for target 'run' failed
make: *** [run] Error 2

**Comment by yentsanglee** [comment] 2020-08-31 18:57
@VincenzoGallicchio This error "2020-08-25T10:47:54.000000Z [(H)ERROR] tid(0x7fbeef90b1c0) | Platform TCB (4) is not up-to-date" indicates that your SGX platform TCB is not up-to-date. Please **ensure that your SGX firmware and software are both updated**. You may run attested TLS sample by

> OE_LOG_LEVEL=INFO make run

which gives your verbose output for you to root cause the problem.

**Comment by yentsanglee** [comment] 2020-09-16 03:45
It has been 2 weeks. I am closing the issue. 

@VincenzoGallicchio let me know if you are still blocked.

**Closed by yentsanglee** 2020-09-16 03:45 UTC
Labels: question, samples, triaged
