### ISSUE TITLE
Doesn't run on Azure's ACC Ubuntu 16.06

### ISSUE THREAD

**Issue by gogo9th** [openenclave/openenclave#2054] opened 2019-07-23 23:38 UTC
Hi,

I installed OpenEnclave on Azure's ACC 16.04 virtual machine based on the instruction here: 
OpenEnclave Github](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md)

However, if I do "make run", I get the following error: 

:samples/helloworld$ make run
host/helloworldhost ./enclave/helloworldenc.signed
23:23:48:708676 tid(0x7fb7e7d3e740) (H)[ERROR]enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR)[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/sgxload.c oe_sgx_create_enclave:535]
23:23:48:708741 tid(0x7fb7e7d3e740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/create.c oe_sgx_build_enclave:558]
23:23:48:708988 tid(0x7fb7e7d3e740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/create.c oe_create_enclave:681]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
Makefile:17: recipe for target 'run' failed
make: *** [run] Error 1

Is there a way to solve this error and get SGX to run properly in a hardware mode of Azure's Ubuntu VM?

**Comment by gogo9th** [comment] 2019-07-23 23:58
If I type from Azure's Ubuntu 18.04 and 16.04:

:samples/helloworld$ oesgx
CPU does not support SGX

However, aren't Azure's Ubuntu 16.04 and Ubuntu 18.04 supposed to support SGX? Or is there a special configuration I should consider when creating these VMs?

**Comment by jxyang** [comment] 2019-07-24 00:27
@johnkord @pushkarcMS

**Comment by Kushg02** [comment] 2019-07-24 21:57
Same issue as above, except running on Ubuntu 16.04 bare metal, issue #2053

**Comment by johnkord** [comment] 2019-07-24 22:15
Specifically, in Azure, you'll need to use either one of these VM sizes: Standard_DC2s or Standard_DC4s.

@gogo9th How did you deploy your ACC VM? Did you do this through the Azure Confidential Compute marketplace offering, or using oe-engine?

@Kushg02 I don't believe SGX features are (currently) enabled on (non-ACC) Ubuntu 16.04 systems.

**Comment by pushkarcMS** [comment] 2019-07-25 17:32
To use SGX in Azure, you need to deploy ACC VMs also known as DC series VM sizes.  Details here: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general#dc-series    
The easiest way to deploy these VMs is through the ACC portal available here: https://aka.ms/ccvm.  Alternatively, you can use oe-engine to generate Azure's reference ARM templates which can be used for azure deployments.

@Kushg02 , the hardware recommendation for OE includes support for SGX1 + Flexible Launch Control (FLC).  Please ensure that any hardware/bare metal system you explore supports these features.  This is the recommended configuration.  If your system does not support FLC, please use the steps outlined here: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md
I am adding generic link for getting started here as well incase you would like to explore different support configurations.
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md

**Comment by Kushg02** [comment] 2019-07-25 21:06
@johnkord @pushkarcMS My machine supports SGX, runs Ubuntu 16.04, and I followed the the instructions of both of those files. I understand this was intended for use in ACC vms, but shouldn't oe work on my system? Especially since I was able to use it before, but am only now I am having issues.

**Comment by johnkord** [comment] 2019-07-25 21:37
@Kushg02 can you check if either of these devices exist on your system?

/dev/isgx
/dev/sgx

Since your machine supports SGX, I imagine that one of these devices should exist if the proper driver is installed.
Can you run: `lsmod | grep sgx` and comment what it prints out?

Do you happen to remember which driver you installed? Was it the SGX driver, or the SGX DCAP driver? If your system doesn't support FLC, then you need to install the SGX driver. Let's try to get to the bottom of this :)

**Comment by Kushg02** [comment] 2019-07-25 21:57
```bash
kush@kush-desktop:~$ lsmod | grep isgx
isgx                   45056  0
```
It was the SGX driver not the DCAP. Do I need to use a specific version? 

Thank you so much for your help, I really appreciate it!

**Comment by johnkord** [comment] 2019-07-25 22:36
Okay that's great. Looks like the right driver is installed for your system! You should see /dev/isgx as a file on your system.

Can you check if the aesm service is running on your system? You can check by running `ps -aef | grep aesm` 

If the aesm service isn't running, you can get an OE_PLATFORM_ERROR I believe

**Comment by gogo9th** [comment] 2019-07-26 00:19
I finally got a DC VM allocated from https://aka.ms/ccvm and my openenclave's sample apps work fine in this VM. I also tried to additionally install Intel's [SGX SDK](https://github.com/intel/linux-sgx) and this one also works fine. However, if I install Intel's [Linux SGX 2 Driver](https://github.com/intel/linux-sgx-driver/tree/sgx2), this one breaks everything. I am just curious why additionally installing Intel's SGX2 Driver makes things not to work... 

Thanks very much for all your help!

**Comment by johnkord** [comment] 2019-07-26 16:04
@gogo9th That's great news!

I think SGX2 isn't supported on DC hardware. Just SGX1 with FLC, from what I understand

**Comment by gupta-ak** [comment] 2019-08-06 02:29
@johnkord The SGX2 features aren't supported by the DC hardware, but the SGX 2.0 driver should work on the DC hardware according to [this](https://github.com/intel/linux-sgx-driver/tree/sgx2
):
> SGX 2.0 Linux Driver (sgx2 branch)
>
> The sgx2 branch of the linux-sgx-driver project contains the SGX 2.0 Linux Driver. This driver has additional support for SGX 2.0-based features available in upcoming CPUs. This driver has the same behavior as the SGX 1.5 Linux Driver (master) on CPUs without SGX 2.0 support.

Note that the previous driver is deprecated in favor of the SGX2 driver, so we need to figure out why it's broken.

**Comment by johnkord** [comment] 2019-08-06 06:28
@gupta-ak Interesting, let's investigate this!

**Comment by johnkord** [comment] 2019-08-13 17:42
Closing this issue now as we have probably resolved the error. As for the SGX2 issue, we've created another issue to track that.  Let us know if we missed anything! :)

**Closed by johnkord** 2019-08-13 17:42 UTC
