### ISSUE TITLE
Inclusion of new headers for doxygen build breaks generated globals.html

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#3866] opened 2021-03-03 02:16 UTC
Per @binxing in #3652:
> Today I added/formatted doxygen comments to both `sgx/seal.h` and `bits/seal.h`, along with other minor formatting changes. Somehow the generated `globals.html` got shortened (just `make doxygen` and open `share/doc/openenclave/html/globals.html` and you'll know what I mean) and I suspect that's a bug of doxygen, as removing *any* of the headers from `docs/refman/CMakeLists.txt` would get `globals.html` back to normal. Maybe we have too long a list of header files for doxygen?

**Comment by rs--** [comment] 2021-04-03 02:01
After further investigation, due to the growing number of entries, [globals.html (v0.14)](https://openenclave.io/apidocs/v0.14/globals.html) is split up into multiple files; [globals.html (v0.15)](https://openenclave.io/apidocs/v0.15/globals.html), [globals_o.html (v0.15)](https://openenclave.io/apidocs/v0.15/globals_o.html), [globals_q.html (v0.15)](https://openenclave.io/apidocs/v0.15/globals_q.html).

Closing this issue, given that this seems to be the expected behaviour of Doxygen.

**Closed by rs--** 2021-04-03 02:01 UTC
Labels: documentation, investigation, triaged
