### ISSUE TITLE
Bug in edger8r import code

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2958] opened 2020-04-28 23:22 UTC
Let's say my enclave application has an edl file called `swithchless.edl` which imports some system edl

```
// switchless.edl
enclave
{
   from "sgx/switchless.edl" import *;

   trusted
   {
      int sample_ecall();
   };

   untrusted
   {
      int sample_ocall();
   }
};
```

Because the system EDL file `sgx/switchless.edl` has the same name as the enclave's EDL file, the code generator (`tools/oeedger8r/intel/CodeGen.ml`) will not import the system EDL file, thinking it has already seen it even though they're different files.

**Comment by radhikaj** [comment] 2020-05-04 18:08
@anakrish  will investigate and possibly submit a PR upstream to Intel SGX SDK

**Comment by llly** [comment] 2020-05-06 02:05
Importing EDL file with same name from different folder is supported by the code generator.
should be careful with  `--search-path` option in this scenario. 

I think the failure of sample `switchless.edl` is caused by syntax error.
`public` key word and semicolon after untrusted section are missed. Should be
```
// switchless.edl
enclave
{
   from "sgx/switchless.edl" import *;

   trusted
   {
      public int sample_ecall();
   };

   untrusted
   {
      int sample_ocall();
   };
};
```

**Comment by jhand2** [comment] 2020-05-06 03:08
I just wrote that free-hand as an example. In actual usage edger8r doesn't fail, it just silently only includes one of the files.

When checking for duplicates the parser strips out the path, so the path you import from doesn't seem to be relevant.

**Comment by llly** [comment] 2020-05-06 05:23
I cannot reproduce your failure. 
I have a sample EDL `sgx_tswitchless.edl`
```
enclave
{
   from "include/sgx_tswitchless.edl" import *;

   trusted
   {
     public int sample_ecall();
   };

   untrusted
   {
      int sample_ocall();
   };
};
```
 SGXSDK is installed in ~ and `~/sgxsdk/include/sgx_tswitchless.edl` is the imported EDL.
Run `oeedger8r sgx_tswitchless.edl --search-path ~/sgxsdk/`. 
Checking sgx_tswitchless_t.h I can see
```
 /**** ECALL prototypes. ****/
int sample_ecall(void);

sgx_status_t sl_init_switchless(void* sl_data);

sgx_status_t sl_run_switchless_tworker(void);

 /**** OCALL prototypes. ****/
oe_result_t sample_ocall(int* _retval);
```
Then I copy `~/sgxsdk/include/sgx_tswitchless.edl`  to `include/sgx_tswitchless.edl`.
Run `oeedger8r sgx_tswitchless.edl` and get same sgx_tswitchless_t.h.

Can you detail the steps of your case?

**Comment by anakrish** [comment] 2020-06-03 17:14
@jhand2 I cannot reproduce this either. Something subtle is different between your scenario and what I and @llly are trying out. Can you specify your exact reproduction steps?

**Comment by jhand2** [comment] 2020-06-03 17:18
hmm, I think the original scenario I proposed was wrong. I I think it's this one that doesn't work:

```
enclave
{
   from "switchless.edl" import *;
   from "sgx/switchless.edl" import *;

   trusted
   {
      public int sample_ecall();
   };
};
```

I would need to go back and double check. Sorry for the confusion

**Comment by llly** [comment] 2020-06-04 01:16
May be "switchless.edl" and "sgx/switchless.edl" are pointing the same file according to `--search-path` in your case.

**Comment by mingweishih** [comment] 2020-06-29 23:59
Closing the issue as it seems not an issue anymore. Feel free to re-open if needed.

**Closed by mingweishih** 2020-06-29 23:59 UTC
Labels: bug, devtools, triaged
