### ISSUE TITLE
Build failures on Windows

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3443] opened 2020-08-25 10:51 UTC
I'm trying to build OE on Windows and after cmake-configuring the build, I get

    ninja: error: 'cmake_object_order_depends_target_mbedcrypto_static_Debug', needed by 
    'cmake_object_order_depends_target_safecrt_enc_Debug', missing and no known rule to make it

(with `cmake version 3.17.20032601-MSVC_2`). Building the host verification library via `ninja oehostverify` gets further, but then fails during the oeedger build:

    C:\dev\openenclave\tools\oeedger8r-cpp\test\virtual\host.cpp(91): error C2039: 'string': is not a member of 'std'

(probably just a missing #include.) 

During configuration, cmake says it finds the VS2019 compiler:

    -- The C compiler identification is MSVC 19.27.29111.0

When I try to force clang by adding `-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++` it complains about the linker not supporting PDBs:

    TARGET_PDB_FILE is not supported by the target linker.

What's the status of the Windows builds? Is there anything obvious I haven't set up correctly? Perhaps a newer cmake or clang (I installed the recommended 7.0.1)?

**Comment by BRMcLaren** [comment] 2020-08-25 13:36
Hi @wintersteiger , I am not the best to assist your question with regards to linkers, however, you did ask the status of Windows Builds. I wanted to point out this [job](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/pipelines/job/Azure-Windows-Badge/) which provides an up to date status of windows builds. 

Admittedly it only covers the SGXFLCGettingStarted use case, which uses an older version of the build tools. The documentation for setting this up can be found in the [docs](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md#install-project-prerequisites). I am wondering if this is potentially a VS2019 compatibility issue.

**Comment by wintersteiger** [comment] 2020-08-25 13:42
Thanks for the pointer @BRMcLaren! Yes, I found a couple more issues that are likely triggered by a VS2019 that's too new and possibly a clang that's too old. In the meanwhile I managed to get it to build, I'll try to summarize my findings to see whether we can simplify this for others.

**Comment by mingweishih** [comment] 2020-08-25 15:20
This is a duplicate of https://github.com/openenclave/oeedger8r-cpp/issues/39, and will fixed once we update the oeedger8r that the OE currently points to (part of #3366).

**Comment by anakrish** [comment] 2020-08-25 18:05
> make_object_order_depends_target_mbedcrypto_static_Debug

I think this might be due to issues with the cmake that is part of VS 2019 (I vaguely remember having encountered this before).
Installing latest cmake from the official distribution might fix this.

**Comment by wintersteiger** [comment] 2020-08-26 13:34
Thanks @anakrish, you're right, it works fine with the latest cmake.

**Comment by radhikaj** [comment] 2020-08-31 18:08
@wintersteiger , do you have any additional issues you need to be addressed? If not, can you please close this issue?

**Closed** 2020-09-01 08:54 UTC
Labels: build, triaged, windows
