### ISSUE TITLE
cannot find a header file in building with OpenSSL

### ISSUE THREAD

**Issue by jinghe-INTC** [openenclave/openenclave#3745] opened 2020-11-20 08:56 UTC
I tried to config with `cmake .. -DBUILD_OPENSSL=ON` and build, and got a failure:
```
openenclave/common/crypto/openssl/asn1.c:11:10: fatal error: 'openssl/asn1.h' file not found
#include <openssl/asn1.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```
I also tried the last `verified `commit `f83f25b81f7bb629e2fd14c212f077cbc2fb8e7f`, and result was the same as the current latest commit `700e999a144fa6de50fc6af65a74eafdd9b4e76e`.

There is at least one configuration of OpenSSL from the bors system, so is there anything I need to fix on my local machines? Actually the problem is also reproducible on an Azure VM.

**Comment by mingweishih** [comment] 2020-11-20 20:14
@jinghe-INTC Can you verify if the problem resolved with the current master? If not, please reopen the issue.

**Comment by jinghe-INTC** [comment] 2020-11-22 09:05
`opensslcrypto` has already been built before building `oecryptoopenssl` on my machines. The PR #3746 doesn't look change anything for it.

**Comment by jinghe-INTC** [comment] 2020-11-22 09:21
I tried to modify the CMakeList file like below:

```
diff --git a/enclave/crypto/openssl/CMakeLists.txt b/enclave/crypto/openssl/CMakeLists.txt
index 725dca550..2837751d6 100644
--- a/enclave/crypto/openssl/CMakeLists.txt
+++ b/enclave/crypto/openssl/CMakeLists.txt
@@ -29,6 +29,8 @@ enclave_include_directories(oecryptoopenssl PUBLIC

 enclave_include_directories(
   oecryptoopenssl PRIVATE
+  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/3rdparty/openssl/openssl/include>
+  $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/3rdparty/openssl/build/include>
   $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/3rdparty/mbedtls/mbedtls/include>
   $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/3rdparty/mbedtls>)
```

It seems working around the build problem of `oecryptoopenssl ` , however there is a new build problem:

```
[ 42%] Building CXX object tests/tls_e2e/server_enc/CMakeFiles/openssl_tls_server_enc.dir/openssl_server.cpp.o
/home/sgxtest/git/my-oe/tests/tls_e2e/server_enc/openssl_server.cpp:20:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^~~~~~~~~~~~~~~
1 error generated.
tests/tls_e2e/server_enc/CMakeFiles/openssl_tls_server_enc.dir/build.make:70: recipe for target 'tests/tls_e2e/server_enc/CMakeFiles/openssl_tls_server_enc.dir/openssl_server.cpp.o' failed
```

**Comment by jinghe-INTC** [comment] 2020-11-23 01:02
There is no `reopen issue` button available for me on this page. @mingweishih, Could you reopen it for me?

**Comment by mingweishih** [comment] 2020-11-24 01:35
Can you check if #3749 fixes the issue?

**Comment by jinghe-INTC** [comment] 2020-11-25 00:13
The same problem still exists in building **oecryptoopenssl** with the latest commit 1e91fe2214a8ec03a638a05a52b8f1d958400457 on my machines.

**Comment by manojrupireddy** [comment] 2020-11-30 18:16
I could not see any build or link errors when I am building Openssl samples https://github.com/openenclave/openenclave/pull/3750. Did you run make install after building the openssl libraries.

**Comment by mingweishih** [comment] 2020-12-01 23:36
I can see the same failure on https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/1966/pipeline/47. Will try to root cause the issue.

**Comment by mingweishih** [comment] 2020-12-02 02:11
I've root caused the issue, which can be reproduced by building the OE with single thread (-j1). #3758 should fix this.

**Closed** 2020-12-03 19:53 UTC
Labels: bug, build, triaged
