### ISSUE TITLE
oeedger8r - Enclave is in simulation mode when oe_get_create_flags returns 0 

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3602] opened 2020-09-28 17:17 UTC
The flag does not work in oeedger8r-cpp's test.

How to set enclave in hardware mode?

Filed by @yanxue-intel : https://github.com/openenclave/oeedger8r-cpp/issues/38

**Comment by dthaler** [comment] 2020-09-28 17:41
@radhikaj I didn't see a resolution, we should at least add an explanation of the answer when closing.

**Comment by radhikaj** [comment] 2020-09-28 18:38
Please add a comment about the resolution.

**Comment by anakrish** [comment] 2020-09-29 19:50
To summarize:

oeedger8r-cpp repository allows development/testing of oeedger8r outside of SGX hardware. This is important since oeedger8r also generates code for OPTEE enclaves. It tests runtime behavior of generated code by loading enclaves in a "virtual" mode which is akin to simulation mode in OE.
Though the virtual mode has been made to look as much as possible like the OE public API surface, not all APIs have the same behavior since SGX hardware does not exist for oeedger8r-cpp repo (by design).

The strategy for oeedger8r testing is

    lock down generate code in oeedger8r-cpp repo. Most of the generated code is hardware agnostic. These should cover 95% of aspects of generated code.
    Add SGX specific tests for generated code in openenclave repo.

**Closed by anakrish** 2020-09-29 19:50 UTC
Labels: devtools, triaged
