### ISSUE TITLE
oeedger-cpp's error message about “duplicated attribute”  contains absolute path

### ISSUE THREAD

**Issue by yanxue-intel** [openenclave/openenclave#3420] opened 2020-08-20 07:20 UTC
duplicated_size.edl

```
enclave {
    trusted {
        public void ecall_size([out, size = len, size = 1024] char* dst,[in, size = 512, size = len] const char* src,size_t len);
    };
};
```
old version oeedger8r results:
```
oeedger8r /home/xy/duplicated_size.edl
Generating edge routines for the Open Enclave SDK.
error: duplicated attribute: `size'
```
oeedger-cpp result:
```
 oeedger8r /home/xy/duplicated_size.edl                                          
Generating edge routine, for the Open Enclave SDK.
Processing /home/xy/duplicated_size.edl.
error: /home/xy/duplicated_size.edl:7:57 multiple size specifier
```

**Comment by anakrish** [comment] 2020-08-24 18:14
It is on purpose to be more informative. By design. Closing it. Please reopen if you think otherwise.

**Closed by anakrish** 2020-08-24 18:14 UTC
Labels: devtools
