### ISSUE TITLE
Return Better OE_PLATFORM_ERROR messages

### ISSUE THREAD

**Issue by lamouriner** [openenclave/openenclave#2710] opened 2020-03-20 15:39 UTC
I have been working on running the remote_attestation demo and am getting some pretty cryptic and unhelpful error output:
![Screen Shot 2020-03-20 at 11 35 07 AM](https://user-images.githubusercontent.com/35075451/77179439-e0603580-6a9e-11ea-8760-89dea5adee1a.png)

It looks like the DCAP API is returning a "quote3_error_t" error code of 0xe011 but a quick search through their docs and codebase didn't turn anything helpful up for me. 

So, first a question: 
Is there anyone who knows what this error message is?

and then a feature request:
Assuming these error codes exist in the DCAP/SGX driver codebase with some sort of name or description can we import them and print them out so that error messages are a bit more helpful?

**Comment by jhand2** [comment] 2020-03-20 15:56
quote3_error_t is an SGX platform error (returned by the intel platform software) not an OE error.

They are defined here: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/ab8d31d72f842adb4b8a49eb3639f2e9a789d13b/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h

That particular error is:
> SGX_QL_NO_PLATFORM_CERT_DATA
> The platform library doesn't have any platfrom cert data.

As for the feature request, I'm hesitant to maintain a manual map since it could get out of sync with the intel libraries. I would support a document that details the types of platform errors and where you can find the definitions for this error.

**Comment by lamouriner** [comment] 2020-03-20 16:05
Thanks @jhand2 !

Certainly a manual map would be tedious and hard to maintain. I was imagining that these errors are all defined in headers *somewhere* in Intel's codebase, and normally I would take the method of including those headers, though i'm not sure how large that search space is/how tractable that idea is.

If it's a terrible idea, a document that explains platform errors and where you can look them up would be immensely helpful for someopne like me :)

Thanks again!

**Comment by jhand2** [comment] 2020-03-20 16:08
It's definitely good to have some indication of what these platform errors mean, its a problem people trip over often :smile:

I'll leave this issue open so we can come up with something to point people to to better understand the error codes being returned.

**Comment by dthaler** [comment] 2020-03-21 00:42
I see the SGX label was added to this issue, but I would want to make sure that any solution is not sgx specific

**Comment by yentsanglee** [comment] 2020-03-24 06:54
The "quote3_error_t=" was from SGX DCAP driver. This is an SGX specific error.

**Comment by jhand2** [comment] 2020-03-24 15:38
You're right that this particular error is SGX-specific, which is why I originally added the SGX label. But since the reason I'm leaving this open is to document all platform errors, Dave is right that this should apply to all platform errors, not just SGX ones.

**Comment by radhikaj** [comment] 2020-03-24 17:17
#1387 Tracks getting more detailed error messages.

Please let us know if this issue is a duplicate of the above.

**Comment by radhikaj** [comment] 2020-03-31 17:02
@lamouriner Please let us know if this is a duplicate of #1387

**Comment by radhikaj** [comment] 2020-03-31 17:05
We are closing this issue. Please reopen if it needs to be addressed.

**Closed by radhikaj** 2020-03-31 17:05 UTC
Labels: question, suggestion
