### ISSUE TITLE
Generalize DCAP Client consumption in the OE SDK build

### ISSUE THREAD

**Issue by johnkord** [openenclave/openenclave#2218] opened 2019-10-01 21:30 UTC
The OE SDK expects to use the Azure DCAP Client for most of its relevant build configurations. This should be generalized to work with any kind of DCAP Client that implements the DCAP Client interface.

**Comment by yentsanglee** [comment] 2020-02-06 22:02
We are working on this issue.

**Comment by soccerGB** [comment] 2020-02-18 06:09
This is a duplicate of https://github.com/openenclave/openenclave/issues/2177

**Closed** 2020-02-18 06:10 UTC
Labels: attestation, triaged
