### ISSUE TITLE
Testing: Sporadic crypto test failure

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2859] opened 2020-04-14 23:23 UTC
We have seen sporadic failure of this form in different PRs 
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/242/pipeline/52

```bash
=== begin _test_verify_with_crl()

2020-04-14T00:10:23.000000Z [(H)ERROR] tid(0x7fc425a04740) | X509_verify_cert failed!

 error: (23) certificate revoked

 (oe_result_t=OE_VERIFY_REVOKED) [../host/Test failed: ../tests/crypto/crl_tests.c(146): _test_get_dates last.minutes == _time.minutes
```

**Comment by CodeMonkeyLeet** [comment] 2020-04-20 16:06
Is this a dupe of #2617?

**Comment by jhand2** [comment] 2020-04-20 16:38
Yes this is a dup. @anakrish if you agree, can we close this in favor of #2617?

**Closed** 2020-04-20 18:15 UTC
Labels: bug, testing
