### ISSUE TITLE
How to build enclave in production-mode (i.e to be signed by Intel whitelisted key)

### ISSUE THREAD

**Issue by josebraga** [openenclave/openenclave#4792] opened 2023-06-28 20:57 UTC
Hey, sorry for the noob question but I am having a hard time understanding how to compile the enclave in production mode. I've gone thru a different docs but need help:

in my `*.conf` file I set `Debug=0` and pass no flags when creating the enclave. I can see on `oesign dump` that debug is no longer set, however since I am able to then launch the enclave this means this is not Production-mode (as I do not yet have a verified Intel key), as if it was I'd expect an error

What am I missing here? Thanks for the support

**Comment by mingweishih** [comment] 2023-06-28 21:12
`Debug` value has nothing to do with production mode, while it's highly recommended.

You can use your own key to sign the enclave for production (i.e., you don't need an intel key). The whitelisting is done via launch control, please refer to: https://github.com/intel/linux-sgx/blob/master/psw/ae/ref_le/ref_le.md for more details.

**Comment by josebraga** [comment] 2023-06-28 21:21
Had not seen this before :open_mouth: 
Is this the only way to build a production-ready enclave ? By production ready I mean one that is able to get a production IAS attestation after.

Thanks for the help :raised_hands:

**Comment by mingweishih** [comment] 2023-06-28 21:34
As long as you run a signed enclave on SGX-capable environment, you should be able to perform remote attestation against the enclave. At a high level, SGX remote attestation with OE works as follows.

- Enclave generates a evidence via `oe_get_evidence` API
  - Under the hood, the API get a local report from CPU and then ask `quoting enclave` from Intel to sign the report. The signed report will be included as part of the output evidence.
- Now the enclave can send the evidence to a remote party (e.g., a verifier such as Microsoft Azure Attestation)
- The verifier uses `oe_verify_evidence` API to verify the `evidence`.
  - Under the hood, the API validates the signature of report against Intel root of trust
  - Also, validates the report with collateral fetched from Intel to ensure the SGX environment is up-to-date.

Please refer https://github.com/openenclave/openenclave/tree/master/samples/attestation for an example.

**Comment by josebraga** [comment] 2023-06-29 09:14
We are aiming for Intel own's EPID attestation process. Does that affect your replies in any way?

In the SGX documentation it's mentioned a 2-step signing process for production (whitelisted) enclaves
(1) First generate the enclave signing material (`*.hex` file, via `sgx_sign gendata`), then sign it, then take the resulting signature and (2) sign the enclave (`sgx_sign catsig`). The process is clear in my mind this way

From your replies I understand this is not required for open enclave, as long as the signature used is whitelisted via the launch control process - is this correct?

One thing that is confusing me is that Intel is clear about "You cannot launch the enclave in non-debug mode (also called production mode) without Intel signing the enclave." -  I'd expect the same constraint building an enclave via openEnclave, i.e, if I set the flags accordingly, the enclave will fail to launch (or be created) due to lack of signature <-  but I don't see any other flags or configurations I can pass

:pray: thanks!

**Comment by josebraga** [comment] 2023-07-03 17:04
I cannot seem to advance.

In one repository this is mentioned about **OpenEnclave**:

> Note that it abstracts DCAP attestation and requires FLC-compatible CPUs. It does not support EPID attestation.

I know I at least can produce **EPID** quotes and get them verified by Intel (albeit `dev` API only thus far)

Doc `samples/attestation` states:

> Note: Unlike the local SGX functionality, currently the remote SGX functionality only works on SGX-FLC systems. The underlying SGX library support for end-to-end remote attestation is available only on SGX-FLC systems. There is no plan to back port those libraries to either an SGX1 system or simulation mode.

As I understand FLC was introduced to support DCAP (3rd party verification),... so...

**Question**: does this mean that with OpenEnclave I can only get a "Production mode" enclave via ECDSA / DCAP attestation? What am I missing ?

**Comment by mingweishih** [comment] 2023-07-07 21:07
You should be able to generate evidence signed with EPID using `oe_get_evidence`: https://github.com/openenclave/openenclave/blob/master/include/openenclave/attestation/sgx/evidence.h#L108

Just note that you would need to use in-proc attestation (`SGX_AESM_ADDR` env var should be undefined).

**Comment by josebraga** [comment] 2023-07-21 18:55
An update: 

After some interactions we understood EPID is a being fased out so we opted for DCAP

For EPID I was using `oe_get_evidence` successfully to get the quote. Running inside a ACC VM, I simply replaced `libsgx-dcap-default-qpl` with `az-dcap-client` to get it working for ECDSA attestation. I was able to get a quote but then MAA attestation was kept failing. (*)

Looking at Azure Code Samples they show `oe_get_report` so I gave it a shot and I started getting a JWT and OK 200 from the service. Now:

1. I notice I still get OK if no `runtimeData` field is provided - this is their field where they mention enclave held data can be placed
2. How can I know why it fails ? In the docs it is mentioned the need to update BIOS for non-Acc machines. [Here](/home/jb/workspace/code/openenclave/docs/DesignDocs/AttestationQPLEnforcementSupport.md) it is mentioned certificate rotation.

Is `oe_get_report` a valid and conclusive method to be used? I.e, our needs is that we want clients to be sure of the code running in the enclave. We don't need to share the report with other enclaves, nor verify it via open enclave.


Thanks for the support

(*) small snippet of the error:
> {"error":{"code":"InvalidQuote","message":"Attestation Enclave operation failed with 65534: RETURN_IF_ERROR('RetrieveAttestationPolicyOcall( _ocallHandle, tenantName, teeKind, policyKind, &localAttestationPolicyBlob)') failed with 0x78: 'No data was provided.'\r\noe_verify_evidence failed with quote collateral error 0x3 - OE_INVALID_PARAMETER: 0xfffe: 'The specified quote was invalid due to an error in the quote collateral.;

**Comment by mingweishih** [comment] 2023-07-21 19:06
@gkostal can you chime in?

**Comment by gkostal** [comment] 2023-07-21 19:24
@josebraga - if you can provide me with the value for the x-ms-request-id response header, I can investigate.  Here's an example curl command that shows this header being returned.

C:\tmp>curl -i https://sharedeus.eus.attest.azure.net/certs
HTTP/1.1 200 OK
Content-Length: 27560
Content-Type: application/json; charset=utf-8
Date: Fri, 21 Jul 2023 19:19:56 GMT
Server: Kestrel
**x-ms-request-id: 00-f12b8b8f42ae7a42f32964501377a667-0000000000000000-00**
x-ms-maa-service-version: 1.11.02357.1216

**Comment by josebraga** [comment] 2023-07-21 19:54
Oh awesome :raised_hands: 

here's the response
```
HTTP/2 200 
content-type: application/json; charset=utf-8
date: Fri, 21 Jul 2023 19:53:21 GMT
server: Kestrel
content-length: 27576
x-ms-request-id: 00-23983dae3494266275775ac3984d09c1-0000000000000000-00
x-ms-maa-service-version: 1.11.02357.1216
```

**Comment by gkostal** [comment] 2023-07-21 19:58
That looks like the response for the curl command.  :-)  That was just an example to show you what the header looked like.  I need the response header when returned for your request that's failing.

**Comment by josebraga** [comment] 2023-07-21 20:09
Oh I see - this was from a quote sent to `/attest/OpenEnclave?api-version=2022-08-01`

`oe_get_evidence` quote gets me 400 HTTP Error:
```
Content-Type:[application/json; charset=utf-8]
Date:[Fri, 21 Jul 2023 20:06:03 GMT]
Server:[Kestrel]
X-Ms-Maa-Service-Version:[1.11.02357.1216]
X-Ms-Request-Id:[00-37e0576435a45fa8aa8819ee9137f0b2-0000000000000000-00]
```

`oe_get_report` gets me 200OK
```
Content-Length:[3706]
Content-Type:[application/json; charset=utf-8]
Date:[Fri, 21 Jul 2023 20:08:11 GMT]
Server:[Kestrel]
X-Ms-Maa-Service-Version:[1.11.02357.1216]
X-Ms-Request-Id:[00-c4c194a7eb4949df94f20cafd77ccf3e-0000000000000000-00]
```

**Comment by gkostal** [comment] 2023-07-21 20:11
OK, I believe I found your requests.  I looked at the two most recent 400 HTTP status code responses:

* For one, you've passed an OE quote to the SGX attestation endpoint.  Intel SGX quotes are not interoperable with OE quotes -- you must call the matching MAA REST endpoint based on the type of quote you have.
* For another, the hash of the supplied RuntimeData didn't match the hash value recorded in the report_data field in the quote

**Comment by gkostal** [comment] 2023-07-21 20:15
> oe_get_evidence quote gets me 400 HTTP

That is by design.  `/attest/OpenEnclave`  does not support verifying the results of `oe_verify_evidence`, only the results of `oe_get_report`.

**Comment by josebraga** [comment] 2023-07-21 21:44
I can't get it to work . 

A few doubts:
1. you say "does not support verifying the results of oe_verify_evidence" , but I am not calling it anywhere, only oe_get_evidence and then passing the output to the MAA

2. The latest two requests you mentioned probably were sometime ago, when I was making attempts.
If I call

```
oe_get_report(OE_REPORT_FLAGS_REMOTE_ATTESTATION, report_data, sizeof(report_data),
        NULL, 0,  &evidence_in,  &evidence_size_in);
// OR

oe_get_evidence(OE_FORMAT_UUID_SGX_ECDSA, OE_EVIDENCE_FLAGS_EMBED_FORMAT_ID, report_data,
        sizeof(report_data), nullptr, 0, &evidence_in,  &evidence_size_in, nullptr, 0)
```

won't both return me OE quotes (and as I understand some form of `oe_header` types with embed sgx quote ?


3. besides `oe_get_report` being phased out, any other downsides of using it for attestation? I ask because time for my delivery is getting short, and somehow, MAA replies OK if I used oe_get_report

**Comment by gkostal** [comment] 2023-07-21 22:11
Apologies on the confusion.  

**re: oe_get_report vs oe_get_evidence**

The MAA REST endpoint at `/attest/OpenEnclave` requires that the `report` field in the `AttestOpenEnclaveRequest` structure contain the results of the call to `oe_get_report`.  The MAA `/attest/OpenEnclave` REST endpoint does not support the results of `oe_verify_evidence`.

https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-open-enclave?tabs=HTTP#attestopenenclaverequest

**re: oe_get_report being phased out**

That's the first I've heard of that.  @mingweishih - is OE phasing out `oe_get_report`?

**Comment by mingweishih** [comment] 2023-07-21 22:53
> Apologies on the confusion.
> 
> **re: oe_get_report vs oe_get_evidence**
> 
> The MAA REST endpoint at `/attest/OpenEnclave` requires that the `report` field in the `AttestOpenEnclaveRequest` structure contain the results of the call to `oe_get_report`. The MAA `/attest/OpenEnclave` REST endpoint does not support the results of the call to `oe_verify_evidence`.
> 
> https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-open-enclave?tabs=HTTP#attestopenenclaverequest
> 
> **re: oe_get_report being phased out**
> 
> That's the first I've heard of that. @mingweishih - is OE phasing out `oe_get_report`?

After the introduction of oe_get_evidence, we only keep oe_get_report for legacy reasons. However, we don’t have plan to deprecate the API anytime soon.

**Closed** 2023-07-25 14:55 UTC
