### ISSUE TITLE
Verify expected behavior if both the OE SDK and host verification library are installed

### ISSUE THREAD

**Issue by gupta-ak** [openenclave/openenclave#2109] opened 2019-08-16 20:04 UTC
Here are some of the open issues and work items for host verification library:

- [x] Name of the package. We internally refer it as the "host verification library" but that probably doesn't make sense to external people. If anyone has a good name, feel free to contribute. The purpose of the package is to provide APIs for validating reports in non-TEE environments.

- [x] Set up CI/CD + nightly build for the new package. Since the host verification package depends on OE report from a TEE machine, this needs to be a pipeline process where we generate the quote first and then send it to the non-TEE VM to verify.

- [x] Documentation and a sample that illustrates how the package works.

- [x] Expected behavior if both the OE SDK and host verification library is installed.

- [x] The host verification library adds a new header file. Consider having the OESDK's `host.h` #include it so that that OE SDK is a superset of the host verification library. The report validation logic is exactly the same, so they are compatible.

- [x] Packing story on Windows. Hopefully, it's as simple as the Debian packaging.

- [x] Add unit tests to run in Linux.

- [x] Add unit tests to run in Windows.

- [x] Port client sample to run in Windows.

**Comment by CodeMonkeyLeet** [comment] 2019-08-16 20:47
FYI @soccerGB, these should probably be broken up into separate issues based on your assignment of resources.

**Comment by jazzybluesea** [comment] 2019-08-20 16:46
How about naming this package "standalone OE certificate validation library"?

**Comment by radhikaj** [comment] 2020-03-31 21:40
Dropping larrywxyz from assignees

**Comment by dthaler** [comment] 2020-06-17 18:27
The CI/CD work is now covered by issue #2519 

A sample was added in PR #2865 

The documentation work is now covered by issue #2513 and #2724 

So the only bullet not already covered by its own issue is "Expected behavior if both the OE SDK and host verification library is installed".  Per SIG-Attestation meeting, updating the title to scope this issue to that remaining bullet.

**Comment by ryanhsu19** [comment] 2020-06-17 19:29
A quick experiment on Ubuntu 18.04 revealed that

- Expected behavior if both the OE SDK and host verification library is installed

is still something we need to work on.

@dthaler since you updated the title already, I do not have to open another issue just to cover the only open bullet, right?

**Comment by dthaler** [comment] 2020-06-17 19:45
@ryanhsu19 correct!

**Comment by yentsanglee** [comment] 2020-07-24 22:48
#2519 covers CI/CD tests.

**Comment by ryanhsu19** [comment] 2020-09-22 00:07
Suppose the filenames for OE and OE SDK Debian packages are `open-enclave.deb` and `open-enclave-hostverify.deb`. Here are some observations:

1. If I do `sudo dpkg -i open-enclave.deb` before doing `sudo dpkg -i --force-overwrite open-enclave-hostverify.deb`, then both packages will be installed despite some warnings against overwriting existing files.
2. Same for doing `sudo dpkg -i open-enclave-hostverify.deb` before doing `sudo dpkg -i --force-overwrite open-enclave.deb`; the only difference is that the first package will be fully replaced and disappear.
3. If I remove the aforementioned `--force-overwrite`, then I am able to install either package, but not both.

Considering that there may be different versions involved, Yen and I discussed the issue and consider it better to let users know that there is something wrong with installing two packages at the same time. Therefore, we consider it the expected behavior.

Will check the 4th work item and close the issue.

**Comment by ryanhsu19** [comment] 2020-09-22 03:11
Close #2109

**Closed** 2020-09-22 04:09 UTC
Labels: attestation, triaged, windows
