### ISSUE TITLE
Child_process tests are failing for ctest on SGX1 LLC

### ISSUE THREAD

**Issue by specio** [openenclave/openenclave#3942] opened 2021-04-07 13:50 UTC
Hi,
I'm running Build&Test on latest master of OE.
OS version: Ubuntu 18.04
CPU used: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
(Supporting LLC only)
```
     SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
```

**All tests except child_process are passing.**

```
99% tests passed, 4 tests failed out of 945

Total Test time (real) = 370.62 sec

The following tests did not run:
	 78 - tests/mbedtls_tls_e2e (Skipped)
	 79 - tests/mbedtls_tls_e2e-lvi-cfg (Skipped)
	 80 - tests/openssl_tls_e2e (Skipped)
	 81 - tests/openssl_tls_e2e-lvi-cfg (Skipped)
	 94 - tests/attestation_cert_api_mbedtls (Skipped)
	 95 - tests/attestation_cert_api_mbedtls-lvi-cfg (Skipped)
	 96 - tests/attestation_cert_api_openssl (Skipped)
	 97 - tests/attestation_cert_api_openssl-lvi-cfg (Skipped)
	 98 - tests/attestation_plugin_mbedtls (Skipped)
	 99 - tests/attestation_plugin_mbedtls-lvi-cfg (Skipped)
	100 - tests/attestation_plugin_openssl (Skipped)
	101 - tests/attestation_plugin_openssl-lvi-cfg (Skipped)
	102 - tests/attestation_plugin_cert_mbedtls (Skipped)
	103 - tests/attestation_plugin_cert_mbedtls-lvi-cfg (Skipped)
	104 - tests/attestation_plugin_cert_openssl (Skipped)
	105 - tests/attestation_plugin_cert_openssl-lvi-cfg (Skipped)
	108 - tests/bigmalloc (Skipped)
	109 - tests/bigmalloc-lvi-cfg (Skipped)
	410 - tests/report_attestation_without_enclave (Skipped)
	411 - tests/report_attestation_without_enclave-lvi-cfg (Skipped)

The following tests FAILED:
	935 - tests/child_process_ecall (Child aborted)
	936 - tests/child_process_ecall-lvi-cfg (Child aborted)
	937 - tests/child_process_destroy (Child aborted)
	938 - tests/child_process_destroy-lvi-cfg (Child aborted)
Errors while running CTest
```
Strace Tail(50)

```
pipe([9, 10])                           = 0
epoll_ctl(8, EPOLL_CTL_ADD, 9, {EPOLLIN|EPOLLET, {u32=9, u64=9}}) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 11
connect(11, {sa_family=AF_UNIX, sun_path="/var/run/aesmd/aesm.socket"}, 110) = 0
epoll_ctl(8, EPOLL_CTL_ADD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
fcntl(11, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(11, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
write(11, "\275\1\0\0", 4)              = 4
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
write(11, "\32\272\3\n E\337\377\205\317+\204d\333@\v\343\362\204^\352j.\262\364\347hPG>\240\214"..., 445) = 445
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLIN|EPOLLET, {u32=11, u64=11}}) = 0
read(11, 0x1800050, 4)                  = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(8, [{EPOLLIN, {u32=11, u64=11}}], 12, 15000) = 1
read(11, "8\1\0\0", 4)                  = 4
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLIN|EPOLLET, {u32=11, u64=11}}) = 0
read(11, "\32\265\2\10\0\22\260\2\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 312) = 312
epoll_ctl(8, EPOLL_CTL_MOD, 11, {EPOLLET, {u32=11, u64=11}}) = 0
close(8)                                = 0
close(9)                                = 0
close(10)                               = 0
close(11)                               = 0
ioctl(5, _IOC(_IOC_WRITE, 0xa4, 0x2, 0x18), 0x7ffea0f0d790) = 0
getcwd("/jenkinsdata/workspace/Pipelines/OpenEnclave-TestInfra/openenclave/build/tests/child_process", 4096) = 93
lstat("/jenkinsdata/workspace/Pipelines/OpenEnclave-TestInfra/openenclave/build/tests/child_process/enc", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/jenkinsdata/workspace/Pipelines/OpenEnclave-TestInfra/openenclave/build/tests/child_process/enc/child_process_enc", {st_mode=S_IFREG|0755, st_size=2795208, ...}) = 0
munmap(0x7f1aafcad000, 2797568)         = 0
munmap(0x7f1aaf9eb000, 2891776)         = 0
futex(0x65c5ec, FUTEX_WAKE_PRIVATE, 2147483647) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f1ab178ea10) = 4366
getpid()                                = 4365
fstat(1, {st_mode=S_IFREG|0664, st_size=161380, ...}) = 0
munmap(0x7f1aae000000, 16777216)        = 0
wait4(-1, Test failed: ../tests/child_process/host/host.cpp(136): main result == OE_OK
[{WIFSIGNALED(s) && WTERMSIG(s) == SIGABRT && WCOREDUMP(s)}], 0, NULL) = 4366
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=4366, si_uid=1000, si_status=SIGABRT, si_utime=2, si_stime=1} ---
wait4(-1, 0x7ffea0f0edc8, 0, NULL)      = -1 ECHILD (No child processes)
write(2, "Test failed: ../tests/child_proc"..., 79Test failed: ../tests/child_process/host/host.cpp(149): main child_status == 0
) = 79
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 4365
gettid()                                = 4365
tgkill(4365, 4365, SIGABRT)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=4365, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
```

What is the purpose of these tests?
Is it expected to pass on SGX1 non FLC platforms.
If so, how to fix them?

+@MWShan @sfblackl

**Comment by mingweishih** [comment] 2021-04-07 19:57
what linux kernel version you're running on?

**Comment by specio** [comment] 2021-04-08 07:55
Linux version 4.15.0-76-generic (buildd@lcy01-amd64-029) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020

**Comment by mingweishih** [comment] 2021-04-08 18:40
what about the version of sgx dcap driver?

**Comment by specio** [comment] 2021-04-09 08:33
Its Legacy Launch Control, there is no DCAP driver.

I'm setting docker image with (most relevant part of dockerfile):
 ```
    ...
    apt update && \
    apt upgrade -y && \
    apt install -y linux-headers-$(uname -r) && \
    apt install sudo -y && \
    getent group && \
    cd /oe/scripts/ansible && \
    sudo ./install-ansible.sh && \
    sudo ansible-playbook ./oe-contributors-setup-sgx1.yml -vvvv && \
    ./remove-ansible.sh && \
    sudo apt-get -y install libsgx-launch libsgx-urts && \
    sudo apt-get -y install libsgx-epid libsgx-urts && \
    sudo apt-get -y install libsgx-quote-ex libsgx-urts && \
    ...
```

bionic.yml vars:
```
intel_sgx_w_flc_driver_url: "https://download.01.org/intel-sgx/sgx-dcap/1.10/linux/distro/ubuntu18.04-server/sgx_linux_x64_driver_1.41.bin"
intel_sgx1_driver_url: "https://download.01.org/intel-sgx/sgx-linux/2.13/distro/ubuntu18.04-server/sgx_linux_x64_driver_2.11.0_0373e2e.bin"
intel_sgx_package_dependencies:
  - "libprotobuf10"
```

Versions:
```

root@902f2dd0a067:/# dpkg --list | grep sgx
ii  libsgx-ae-epid                  2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions QE and PvE
ii  libsgx-ae-le                    2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions LE
ii  libsgx-ae-pce                   2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions PCE
ii  libsgx-ae-qe3                   1.10.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions QE3
ii  libsgx-ae-qve                   1.10.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions QVE
ii  libsgx-aesm-ecdsa-plugin        2.13.100.4-bionic1                         amd64        ECDSA Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-epid-plugin         2.13.100.4-bionic1                         amd64        EPID Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-launch-plugin       2.13.100.4-bionic1                         amd64        Launch Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-pce-plugin          2.13.100.4-bionic1                         amd64        PCE Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-aesm-quote-ex-plugin     2.13.100.4-bionic1                         amd64        Unified Quote Plugin for Intel(R) Software Guard Extensions AESM Service
ii  libsgx-enclave-common           2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions Enclave Common Loader
ii  libsgx-epid                     2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions EPID Quote Service
ii  libsgx-launch                   2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions Launch Service
ii  libsgx-pce-logic                1.10.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-qe3-logic                1.10.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
ii  libsgx-quote-ex                 2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions Unified Quote Service
ii  libsgx-urts                     2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions uRTS
ii  sgx-aesm-service                2.13.100.4-bionic1                         amd64        Intel(R) Software Guard Extensions AESM Service

```

Host machine is passing isgx driver to docker:

```
specio@oenc-host:~$ modinfo isgx
filename:       /lib/modules/4.15.0-76-generic/kernel/drivers/intel/sgx/isgx.ko
license:        Dual BSD/GPL
version:        2.11.0
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX Driver
srcversion:     87784B58E0AACD186EEF5B6
alias:          acpi*:INT0E0C:*
depends:
retpoline:      Y
name:           isgx
vermagic:       4.15.0-76-generic SMP mod_unload
```
Enclaves are working, just child-process tests are failing.

**Comment by haitaohuang** [comment] 2021-04-09 18:21
Legacy driver does not support enclave shared in forked processes.

**Comment by MWShan** [comment] 2021-04-09 19:53
@haitaohuang - thanks for the response, so can we conclude that the following tests should not be run when Legacy Launch (which must use the Legacy Driver) is used:
	935 - tests/child_process_ecall (Child aborted)
	936 - tests/child_process_ecall-lvi-cfg (Child aborted)
	937 - tests/child_process_destroy (Child aborted)
	938 - tests/child_process_destroy-lvi-cfg (Child aborted)

**Comment by MWShan** [comment] 2021-04-12 19:44
@specio  - can the above tests be removed for the pipeline which tests platforms using Legacy Launch (the Legacy Launch Driver)?

**Comment by BRMcLaren** [comment] 2021-04-20 18:01
@specio @MWShan this was assigned to me, however, the above conversation seems to point @specio owning this. Can I reassign or have I misread the situation?

**Comment by MWShan** [comment] 2021-04-20 18:11
@BRMcLaren - I think that the source of the issue is that a test pipeline running on a platform which is running legacy launch (using the legacy out-of-tree driver) cannot support the child process tests.  Thus, these tests should not be run in that pipeline.  Whomever owns configuring the tests for the pipeline to execute should be assigned this issue (maybe that is @specio?)

**Comment by BRMcLaren** [comment] 2021-04-20 18:18
@MWShan Thanks for the clarification. Reassigning to @specio

**Comment by specio** [comment] 2021-06-02 08:17
Fixed

**Closed** 2021-06-02 08:17 UTC
Labels: SGX, testing, triaged
