### ISSUE TITLE
oesign: successful in signing an enclave using a config file with duplicated fields 

### ISSUE THREAD

**Issue by johnvenn** [openenclave/openenclave#3143] opened 2020-06-17 07:42 UTC
in previous test, before PR 3128, this kind of behavior was not allowed. 

But now it passed.
./oesign sign -e oesign_test_enc -c invalid_syntax_2.conf -k sign_key.private.pem
Created oesign_test_enc.signed

Contents of config file invalid_syntax_2.conf ==>

Debug=1
NumHeapPages=1024
NumHeapPages=1024
NumStackPages=1024
NumTCS=1
ProductID=1
NumHeapPages=1024
NumHeapPages=1024
SecurityVersion=1

could you explain about this change? @CodeMonkeyLeet

**Comment by CodeMonkeyLeet** [comment] 2020-06-17 19:48
Verified that this is not a regression introduced by #3128; the [v0.9 release drop](https://github.com/openenclave/openenclave/releases/download/v0.9.0/open-enclave.0.9.0.nupkg) of oesign will also successfully sign a package given this syntax. In particular, the last repeated value in the list is the value that will be written into the signature. Looking at the source code history, oesign has never enforced duplication of keys as an error. 

If you're wondering why the test you wrote was failing before and not now, note that there was a silent failure in config file generation that was fixed in commit c872bc27d8cabcc55c4663cccd3101c92c0b01f1 to explicitly invoke `python` on the make-oesign-config.py script, prior to that, the negative .conf tests were failing (as expected) but because they were failing to load a non-existent .conf file (wrong reason). The addition of the `PASS_REGULAR_EXPRESSION` checks exposed that failure and that was fixed in the commit.

**Comment by johnvenn** [comment] 2020-06-18 01:00
ok, thanks a lot for the explanation.

**Comment by CodeMonkeyLeet** [comment] 2020-06-18 01:25
Keeping this issue open, because while this behavior is not a regression, we should evaluate whether the existing behavior is desirable. It's certainly not documented anywhere and it is likely surprising for users encountering it.

**Comment by johnvenn** [comment] 2020-06-18 01:29
ok, this is also my concern. Because in SGX design, we don't allow this behavior. The restriction on the syntax is tight, to make it simple.

**Comment by dthaler** [comment] 2020-06-18 01:36
Agree the existing behavior would seem to violate the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).   I think the expected behavior would be to fail if there are any duplicates in the file, and report an error.

**Closed** 2020-06-19 17:03 UTC
