### ISSUE TITLE
Endianness in attestation plugins

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3047] opened 2020-05-18 13:10 UTC
The attestation plugin infrastructure and the SGX plugin currently do not enforce or check endianness of their input and output data structures. Thus, similar to #2266, evidence generated on little-endian machines cannot be verified on big-endian machines by `oe_verify_evidence`. 

This is because of both, the SGX plugin and the plugin infrastructure (e.g. serialization of `oe_attestation_header_t`) not enforcing either endianness. 

(#3007 implements this partly for the EEID plugin and bits may be reusable.)

**Comment by yentsanglee** [comment] 2020-07-22 19:51
Duplicate of #2266

**Closed by yentsanglee** 2020-07-22 19:51 UTC
Labels: attestation, triaged
